#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-


## -------------------------------------------------------------------------------
## -------------------------------------------------------------------------------
# Criado por Carlos Alberto Pedroso
# Data: 07/02/2021
# Para disciplina de Otimização (trabalho 2)
# Professor André Guedes 
## -------------------------------------------------------------------------------
## -------------------------------------------------------------------------------


import elenco
import sys

if __name__ == "__main__":
    elenco.main(len(sys.argv),sys.argv)